name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag scan_image_dev:$(date +%s)

    - name: Tag the Docker image with the repository name
      run: docker tag scan_app_dev:$(date +%s) ogkatzu/scan_app_images:latest

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push the Docker image to Docker Hub
      run: docker push ogkatzu/scan_app_images:latest
